# Generated by Django 5.0.1 on 2024-02-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_anchor_registration_delete_employee_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anchor_registration',
            name='license_no',
        ),
        migrations.AddField(
            model_name='anchor_registration',
            name='previous_work',
            field=models.IntegerField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
