# Generated by Django 5.0.1 on 2024-02-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_anchor_registration_license_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchor_registration',
            name='password',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_registration',
            name='password',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anchor_registration',
            name='experience',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='anchor_registration',
            name='previous_work',
            field=models.CharField(max_length=50),
        ),
    ]
