# Generated by Django 5.0.1 on 2024-02-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_anchor_registration_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchor_registration',
            name='action',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
