# Generated by Django 5.0.1 on 2024-02-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_anchor_registration_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchor_registration',
            name='type_of_anchor',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
