# Generated by Django 5.0.1 on 2024-02-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_anchor_registration_type_of_anchor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ufeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.CharField(max_length=55)),
                ('bname', models.CharField(max_length=555)),
                ('feed', models.CharField(max_length=55)),
            ],
        ),
    ]
