# Generated by Django 5.0.1 on 2024-03-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_afeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchor_registration',
            name='gender',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
