# Generated by Django 5.0.1 on 2024-03-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_type_of_anchor_anchor_registration_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchor_registration',
            name='video',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
