# Generated by Django 5.0.1 on 2024-04-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_anchor_registration_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchor_registration',
            name='about_your_job',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
