# Generated by Django 5.0.1 on 2024-04-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_in',
            name='action',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
