# Generated by Django 5.0.1 on 2024-04-04 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_user_registration_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anchor_registration',
            name='password',
        ),
    ]
