# Generated by Django 5.0.1 on 2024-05-07 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_passwordreset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anchor_registration',
            name='previous_work',
        ),
    ]
