# Generated by Django 5.0.1 on 2024-05-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_anchor_registration_previous_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='action',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
