# Generated by Django 5.0.1 on 2024-05-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_booking_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anchor_registration',
            old_name='pro_pic',
            new_name='profile',
        ),
    ]
