# Generated by Django 5.0.1 on 2024-05-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
