# Generated by Django 5.0.1 on 2024-05-13 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_booking_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='action',
            new_name='ACTION',
        ),
    ]
