# Generated by Django 5.0.1 on 2024-05-13 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_action_booking_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='NAME',
            new_name='username',
        ),
    ]
