# Generated by Django 5.0.1 on 2024-05-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='DATE',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='DATE',
            field=models.DateField(),
        ),
    ]
