# Generated by Django 5.0.1 on 2024-05-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchor_registration',
            name='photo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anchor_registration',
            name='photo1',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anchor_registration',
            name='photo2',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anchor_registration',
            name='photo3',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
