# Generated by Django 5.0.1 on 2024-05-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_anchor_registration_photo_anchor_registration_photo1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='anchor_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='')),
                ('photo1', models.FileField(upload_to='')),
                ('photo2', models.FileField(upload_to='')),
                ('photo3', models.FileField(upload_to='')),
                ('photo4', models.FileField(upload_to='')),
                ('photo5', models.FileField(upload_to='')),
            ],
        ),
    ]
