# Generated by Django 5.0.1 on 2024-05-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_anchor_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='anchor_gallery',
            name='photo1',
        ),
    ]
