# Generated by Django 5.0.1 on 2024-05-23 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_pay_remove_anchor_gallery_photo1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anchor_registration',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='anchor_registration',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='anchor_registration',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='anchor_registration',
            name='photo3',
        ),
    ]
