# Generated by Django 5.0.3 on 2024-05-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_rename_user_passwordreset_user_registration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='afeed',
        ),
        migrations.RenameField(
            model_name='ufeed',
            old_name='bname',
            new_name='anchorname',
        ),
        migrations.RenameField(
            model_name='ufeed',
            old_name='wname',
            new_name='username',
        ),
        migrations.AddField(
            model_name='ufeed',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='DATE',
            field=models.CharField(max_length=50),
        ),
    ]
