# Generated by Django 5.0.1 on 2024-05-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchor_registration',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
