# Generated by Django 5.0.1 on 2024-05-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_anchor_registration_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='amountdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('fixedamount', models.IntegerField()),
                ('advance', models.IntegerField()),
            ],
        ),
    ]
