# Generated by Django 5.0.1 on 2024-05-28 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_amountdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anchor_registration',
            name='price',
        ),
    ]
